#%RAML 1.0 DataType
displayName: Account
description: Defines the fields in Account Datatype

type: object
properties:
  id?: string
  firstName: string
  lastName: string
  address: string
  postal: string
  country: string
  miles: integer
  creationDate?: datetime
  type: string
