#%RAML 1.0 NamedExample

value:
-
  id: "1234"
  firstName: "John"
  lastName: "Doe"
  address: "123 Main St., Dallas TX"
  postal: "77777"
  country: "USA"
  miles: 999
  creationDate: 2019-08-21T04:34:41.098Z
  type: "personal"
-
  id: "8989"
  firstName: "Jane"
  lastName: "Doe"
  address: "10 Downing St., San Francisco CA"
  postal: "89897"
  country: "USA"
  miles: 101
  creationDate: 2018-12-09T21:53:12.127Z
  type: "business"  