#%RAML 1.0 NamedExample

value:
-
  firstName: "John"
  lastName: "Doe"
  address: "123 Main St., Dallas TX"
  postal: "77777"
  country: "USA"
  miles: 999
  type: "personal"
-
  firstName: "Jane"
  lastName: "Doe"
  address: "10 Downing St., San Francisco CA"
  postal: "89897"
  country: "USA"
  miles: 101
  type: "business"  